### ISSUE TITLE
Game Code Sample

### ISSUE THREAD

**Issue by loretoparisi** [JohnSundell/ImagineEngine#1]
Would be great to provide a (very) simple game demo like the ones Apple provides in the Code Examples to better understand how the engine works.

**Comment by JohnSundell** [comment]
Hi @loretoparisi 👋 Totally agree, this is something I’m going to add within the next couple of days 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JohnSundell** [comment]
I've now added the very first tutorial! 🎉 Hope you like it, and let me know if you have any feedback or improvement suggestions 😄 https://github.com/JohnSundell/ImagineEngine/tree/master/Documentation/Tutorials/1-AsteroidBlaster
