### ISSUE TITLE
Add 'resized' event for Camera

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#100]
Similar to how `Actor` has a `resized` event that gets triggered whenever its size changes, we should do the same thing for `Camera`. The nice thing is that this would allow a scene to easily be resized whenever its container view gets resized (since the size of the camera is the same as the size of the view).

**Things to do:**

- Add a `resized` event on `CameraEventCollection`.
- Trigger the new event whenever a camera's size was changed.

**Good to know:**

- Take a look at how the `resized` event works for `Actor`.
- For inspiration on how to test this change, check out `ActorTests`, which includes many tests for events.

**Comment by Warren-Lamb** [comment]
Hey John.  I will give this a go!

**Comment by JohnSundell** [comment]
Fixed in https://github.com/JohnSundell/ImagineEngine/pull/115
