### ISSUE TITLE
Line animation issue! 

### ISSUE THREAD

**Issue by SS-HU** [JohnSundell/ImagineEngine#103]
Dear Mr Sundell. 
Waiting for the promised line animations, but got blocked. Care to explain please?
//SS

**Comment by JohnSundell** [comment]
Hi @SS-HU 👋 What do you mean by line animations? 🤔

**Comment by SS-HU** [comment]
Why did you block me?
//Sina

**Comment by JohnSundell** [comment]
Resolved this with @SS-HU over email 🙂
