### ISSUE TITLE
The Timeline API doesn't allow to repeat an action at random intervals

### ISSUE THREAD

**Issue by dabrut** [JohnSundell/ImagineEngine#105]
It seems like there's no way to repeat an action at random intervals easily.

This could be useful for example if we want to add an enemy to a scene every n seconds (n being randomly generated every time).

The call site could look like this:

```
let intervalGenerator: () -> TimeInterval = { TimeInterval(arc4random_uniform(10)) } 
scene.timeline.repeat(withInterval: intervalGenerator) {
    let enemy = Actor()
    enemy.animation = Animation(name: "Enemy", frameCount: 5, frameDuration: 0.15)
    scene.add(enemy)
}
```

What do you think?

**Comment by JohnSundell** [comment]
Hey @dabrut 👋 How about continously scheduling delayed closures using Timeline's `after()` API?

```swift
class MyScene: Scene {
    func spawnEnemy() {
        let enemy = Actor()
        enemy.animation = Animation(name: "Enemy", frameCount: 5, frameDuration: 0.15)
        add(enemy)

        timeline.after(interval: intervalGenerator(), using: self) { scene in
            scene.spawnEnemy()
        }
    }
}
```

**Comment by dabrut** [comment]
@JohnSundell I was "focused" on the `repeat()` API but this is a totally acceptable alternative 👍 .
Thanks John.
