### ISSUE TITLE
Removing colliding actor sometimes causes extra collision event

### ISSUE THREAD

**Issue by mattiashagstrand** [JohnSundell/ImagineEngine#108]
Here is a test that triggers this bug:

```swift
func testObservingCollisionWhenCollidingActorIsRemoved() {
    actor.size = Size(width: 100, height: 100)
    actor.position = Point(x: 300, y: 300)

    let otherActor = Actor(size: Size(width: 100, height: 100))
    game.scene.add(otherActor)

    var numberOfCollisions = 0

    actor.events.collided(with: otherActor).observe {
        otherActor.remove()
        numberOfCollisions += 1
    }

    XCTAssertEqual(numberOfCollisions, 0)

    // Move the actor to trigger collision detection but not so far that it
    // collides with the other actor.
    actor.position = Point(x: 200, y: 0)
    // Move the other actor so that it collides with the actor
    otherActor.position = actor.position

    XCTAssertEqual(numberOfCollisions, 1)
}
```

Note that for this bug to happen the actor that is removed must be the one that triggers the collision.

Doing the following in ```Grid``` fixes the bug:

```swift
private func detectCollisions(between actor: Actor, and otherActors: Set<Actor>) {
    for otherActor in otherActors {
        guard otherActor !== actor else {
            continue
        }

        guard otherActor.scene != nil else {
            continue
        }

        guard actor.scene != nil else {
            continue
        }

        ...
    }
}
```

I haven't created a PR yet because even though all tests pass I'm unsure if this can cause other bugs.
What do you thing @JohnSundell ?

**Comment by JohnSundell** [comment]
Seems legit to me @mattiashagstrand 👍 An actor shouldn't be able to participate in collisions after it has been removed, and since the set still contains the removed actor it seems like a good idea to check if it has a `scene` property - feel free to submit a PR! 😄

**Comment by JohnSundell** [comment]
This can be closed, right @mattiashagstrand?

**Comment by mattiashagstrand** [comment]
@JohnSundell Absolutely! It was fixed in PR #111

**Comment by JohnSundell** [comment]
@mattiashagstrand Pro tip: If you write "Resolves #<NumberOfIssue>" in your PR description then GitHub automagically closes the issue you fixed 😉

**Comment by mattiashagstrand** [comment]
@JohnSundell Ahh, nice, didn't now about "Resolves #". Will use that from now on... 👍
