### ISSUE TITLE
Fallback to lower scale textures if exact match can't be found

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#11]
In Imagine Engine, images for textures are loaded as `CGImage` directly (not as `UIImage` or `NSImage`, for performance reasons). This means that we don't get the feature of automatically falling back to images of a lower scale if an exact match can't be found.

For example, when loading a `UIImage`, if I specify `UIImage(named: "myImage")` when running on a `@3x` device, the system will first try to load `myImage@3x.png`, then `myImage@2x.png`, and so on. We should make Imagine Engine match this behavior.

The texture loading code can be found in [TextureManager](https://github.com/JohnSundell/ImagineEngine/blob/master/Sources/Core/API/TextureManager.swift).

**Comment by TyrfingMjolnir** [comment]
I have read the content of TextureManager. Not sure what needs to be done, does this have to be done like cycling through "\(imagename)@3x.png" "\(imagename)@2x.png" "\(imagename).png" ? I can loop through the options yet I have the feeling there is a much more desirable functional approach.

**Comment by FranciscoAmado** [comment]
Hi @TyrfingMjolnir,
From what I've seen you can add a small logic in [this line](https://github.com/JohnSundell/ImagineEngine/blob/e385fc0c4f005b651a5d48fcbf7b858035f6951a/Sources/Core/API/TextureManager.swift#L62). It won't be much of an increment and you can pinpoint the problem described.
This could fallback to `load(texture, namePrefix: namePrefix, scale: scale - 1)`
Also, don't forget to add a stop condition before to prevent calling the `load` with an invalid scale (less or equal to 0).

**Comment by JohnSundell** [comment]
Yeah that's a great idea @FranciscoAmado 👍

**Comment by JohnSundell** [comment]
An additional optimization (doesn't have to be part of the initial implementation) would be to remember that fallback so that the next time the same texture is requested, the scale can be corrected right away (to avoid unnecessary I/O trying to load files we already know don't exist).
