### ISSUE TITLE
Extra collision event when actor moves between grid tiles

### ISSUE THREAD

**Issue by mattiashagstrand** [JohnSundell/ImagineEngine#118]
After two actors have collided there is normally only one collision event even if they move around, as long as they remain in contact. However, if one of the actors move out of a grid tile that both actors are in and then moves back into it, an extra event is generated. Here is a test that shows this happening:

```swift
func testObservingCollisionsWhileInContactAndMovingBetweenGridTiles() {
    let otherActor = Actor(size: Size(width: 100, height: 100))
    game.scene.add(otherActor)

    actor.size = otherActor.size
    actor.position = Point(x: 200, y: 0)

    var numberOfCollisions = 0

    actor.events.collided(with: otherActor).observe {
        numberOfCollisions += 1
    }

    XCTAssertEqual(numberOfCollisions, 0)

    // Actors start intersecting = first collision
    actor.position = Point(x: 0, y: 0)
    XCTAssertEqual(numberOfCollisions, 1)

    // Actor moving out of grid tile and then back into it while
    // in contact the whole time
    actor.position = Point(x: 60, y: 0)
    actor.position = Point(x: 40, y: 0)
    XCTAssertEqual(numberOfCollisions, 1)
}
```

This is happening because when an actor leaves a tile the other actors in that tile are removed from ```actorsInContact```:

```swift
for otherActor in tile.actors {
    guard otherActor.actorsInContact.remove(actor) != nil else {
        continue
    }

    actor.actorsInContact.remove(otherActor)
}
```

I noticed that nowhere in ```Grid``` do we check if two actors that were in contact are no longer in contact.

Is this by design to get better performance or is this a bug?

**Comment by JohnSundell** [comment]
@mattiashagstrand This is a shortcut I made for performance reasons, as you suspected. However, I think we should still consider it a bug since it can lead to unexpected behavior. Perhaps we should check if the actors are still in contact before removing them when an actor leaves a grid tile, what do you think?

**Comment by mattiashagstrand** [comment]
@JohnSundell Yes, checking if they are still in contact is a good idea I think and would solve this bug.
