### ISSUE TITLE
Frame by Frame Sprite Control

### ISSUE THREAD

**Issue by jasonmerchant** [JohnSundell/ImagineEngine#132]
How would we achieve frame by frame control over a sprite?

Let's imagine a scenario from another pseudo engine as an example:

Every frame an update() function is called.

Inside update I want to set the current frame for the sprite.

My reasoning is that I want to process all my input controls and interactions with the game world, as well as the past few moments to decide which animation frame to show in the present. 

This would allow some dynamic transitions between animation loops where another input button is pressed before the previous animation completes.

**Comment by JohnSundell** [comment]
Hi @jasonmerchant 👋 

You can use the `Action` API to gain frame by frame control. Create a custom action by subclassing the `Action` class and override `update(with context: UpdateContext)` and run your logic there.

You can then assign a new sprite/texture to an actor like this:

```swift
actor.animation = Animation(textureNamed: "MyTexture")
```

To make an actor perform your action, simply call `perform()`:

```swift
actor.perform(MyAction())
```

**Comment by jasonmerchant** [comment]
Hmm, it sounds like this engine will be really slow for this sort of thing.

What I'm really looking for, is to load the sprite sheet into the gpu ahead of time, and then call something like showFrame(3) which would render that part of the sprite sheet.

I guess I'm back to using Metal.

Anyhow, thanks for clarifying.
