### ISSUE TITLE
Buggy game example

### ISSUE THREAD

**Issue by gerchicov-bp** [JohnSundell/ImagineEngine#14]
I just can't run it. I follow instructions for asteroids game and can't understand even how to run it. Playground is compiled, shows some stats to the right and thats everything that works. Where the screen with working game?

In general your engine is not a `UIKit` control so it is a bad idea to make it as a `playground`:
1)it takes too much time to compile it every time you change the code
2)99% of people will use this engine in a project, not `playground` so it is better to see how to integrate it into project/workspace without playgrounds

**Comment by dymv** [comment]
Along with this line in a playground

```
PlaygroundPage.current.liveView = GameViewController(scene: scene)
```

and that editor being visible

> open the playground's assistant editor (press ⌥+⌘+Enter) you should now see a dark blue rectangle

you should be able to see the result. Please provide more info if that's not the case for you.

**Comment by JohnSundell** [comment]
Hi @gerchicov-bp 👋

As @dymv says, as long as you assign a live view to the playground and open the assistant editor using the instructions in the tutorial, you should see a game running 👍

The reason I made it using a playground is that (in my opinion), it's a super nice way to learn new APIs and make quick experiments. If you don't agree with this, you can totally complete the tutorial in an app project as well (just push the `GameViewController` from the tutorial onto your app's navigation controller, for example).

There will be more tutorials in the future that will show how to integrate Imagine Engine into a proper app, this is just the first one.

Finally, may I suggest that you use a slightly more friendly tone when opening issues on open source projects? This is something me, @dymv & others are working on in our spare time, for fun, so calling someone's work "buggy" and "a bad idea" is not really a great strategy for getting people to help you 🙂
