### ISSUE TITLE
Make Label rotatable

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#152]
You should be able to rotate a Label using the same API that you can use for actors. Functionality like this is implemented in a protocol oriented fashion, so all that needs to be done is to make `Label` conform to `Rotatable`. See `Actor`'s implementation of this protocol for reference.

**Comment by kkapitan** [comment]
I'll take it if it's still open :)

**Comment by jussi80** [comment]
I was just to about to finish this task also. :)

**Comment by JohnSundell** [comment]
Fixed by @jussi80 in #156 🎉
