### ISSUE TITLE
Why do you not make Package?

### ISSUE THREAD

**Issue by seadiem** [JohnSundell/ImagineEngine#169]
What about make package for install it to blank project? You have Source folder already.

**Comment by JohnSundell** [comment]
@seadiem What do you mean? Do you mean let Imagine Engine be installed using the Swift Package Manager? If so, please see [this issue](#154). SPM is currently not very suitable for games. If you mean something else then please clarify 🙂

**Comment by seadiem** [comment]
I'm understand. So main trouble for macOS, that is distribution a ready program? But what about make Resource folder and in code link to that resource thought relative path aka "../Resource" ?

**Comment by JohnSundell** [comment]
That sounds really complicated, compared to just making a standard Mac app and including Imagine Engine either manually or using another package manager like CocoaPods or Carthage (both of which are supported). Until there's a way to package resources using SPM, and creating a "normal" Mac app using it (not only a command line tool or a script), I really don't think it's worth spending any time on supporting it.

Closing this issue for now, and we'll use #154 in case there's any new developments in this area. Thanks anyway for your suggestion 🙂
