### ISSUE TITLE
Event addObserver crash

### ISSUE THREAD

**Issue by marekslk** [JohnSundell/ImagineEngine#176]
After new version of XCode (9.3) my app started to crash with this issue. 

![snimka obrazovky 2018-04-09 o 12 50 22](https://user-images.githubusercontent.com/31618932/38494042-b52f1532-3bf4-11e8-9c68-e2b8f67db4ea.png)
![snimka obrazovky 2018-04-09 o 12 49 53](https://user-images.githubusercontent.com/31618932/38494044-b54e22e2-3bf4-11e8-877a-1a066ff11684.png)

**Comment by JohnSundell** [comment]
Fix is here: https://github.com/JohnSundell/ImagineEngine/pull/177
