### ISSUE TITLE
Any plans to support Non-Apple platforms?

### ISSUE THREAD

**Issue by VioletasTheThird** [JohnSundell/ImagineEngine#186]
Just wondering. The engine looks like it would be great to use, but sadly I'm on Linux. After a quick google, I saw that Swift supports Linux, so I was just wondering if it would be a possibility.

**Comment by JohnSundell** [comment]
Not at the moment, no - since Imagine Engine uses Apple's CoreAnimation framework, which is not available on Linux.

**Comment by shial4** [comment]
Do you consider going to cross-platform at all?

[SDL](https://www.libsdl.org) officially supports Windows, Mac OS X, Linux, iOS, and Android.
Swift can be run on [Android](https://github.com/apple/swift/blob/master/docs/Android.md) (good example is [SCADE](https://www.scade.io) iOS, Mac OS X, Linux & [Windows](https://github.com/apple/swift/blob/master/docs/Windows.md)

SDL is written in C. Which is the biggest advantage for it. We can create a simple wrapper for the library. Isn't that great?  

What is your point of view on that topic? 
@JohnSundell 

Cheers,
Shial

**Comment by JohnSundell** [comment]
I don't, since at the moment I have no interest in building games for platforms other than Apple's platforms. But feel free to fork Imagine Engine and make those modifications if you want to build a cross-platform game using it 🙂
