### ISSUE TITLE
README section with why this engine stands out

### ISSUE THREAD

**Issue by FrankKair** [JohnSundell/ImagineEngine#2]
I think it would be nice to have a section on the README file showing why someone would want to use ImagineEngine over cocos2d or SpriteKit.
Like, what characteristics make this one stand out, why you designed it. 😊

**Comment by JohnSundell** [comment]
That's a great idea @FrankKair! I'll make sure to add that soon as part of the work to improve the documentation and add guides & tutorials 👍

**Comment by MKGitHub** [comment]
That would be really interesting as SpriteKit + SceneKit + GamplayKit are the Apple standard frameworks for building games with high performance + shaders + metal + AR and Xcode integrated editor 😊 I think that this would be for the novice developers with very little knowledge about game development. It would also be interesting to see performance tests compared to SpriteKit 😊
