### ISSUE TITLE
Issue with Walkabout Tutorial

### ISSUE THREAD

**Issue by Adamcbrz** [JohnSundell/ImagineEngine#37]
I am have been trying to go through the Walkabout tutorial. But I can't seem to get stuck at the first couple of steps.

Repo Steps:
1) Download Repo
2) open ImagineEngine/Documentation/Tutorials/2-Walkabout/Walkabout.xcworkspace
3) Hit Command + B to build
4) Add to the playground import ImagineEngine

Result: see the following error:
`Playground execution failed:

error: Playground.playground:3:8: error: no such module 'ImagineEngine'
import ImagineEngine`

Expected Result: That it finds the module and doesn't produce the error.

Mac OSX: 10.12.6
Xcode: 9.0.1

**Comment by Alex88WH** [comment]
Hmm, I had that same problem. Did you finish the first tutorial, right? Clone the repo again and go straight to walkabout tutorial. I don't know why but that worked for me.

**Comment by Adamcbrz** [comment]
@Alex88WH I had my device selected selecting a simulator and rebuilding worked. Thank you!

**Comment by JohnSundell** [comment]
Awesome to hear that things worked out! I'll add a note to the tutorials to make it clear that you need to build Imagine Engine for the simulator 👍
