### ISSUE TITLE
Support retrieving plugins based on type

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#53]
Imagine Engine supports plugins that can be used to extend the functionality of its core objects, such as Actor, Scene and Camera. All objects that can have plugins attached to them conform to the `Pluggable` protocol.

An API should be added on `Pluggable` that enables the user to retrieve plugins based on a type, so you are able to do this:

```swift
let actor = Actor()
actor.add(MyPlugin())

let plugins = actor.plugins(ofType: MyPlugin.self)
```

**Good to know:**

- `Pluggable` defines the API for managing plugins.
- `Pluggable` already has a `removePlugins(ofType:)` API that can be used for inspiration.
- Internally, a `PluginManager` class is used by all objects to manage their plugins.

**Comment by TadeasKriz** [comment]
I’m taking this one

**Comment by TadeasKriz** [comment]
@JohnSundell Since there can be more than one instances of a plugin with the same type, shouldn't this method be `plugins<P: Plugin>(ofType: P.Type) -> [P]`?

**Comment by JohnSundell** [comment]
@TadeasKriz You are completely right 👍
