### ISSUE TITLE
Make a Scene's layer opaque + set black background color

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#55]
Currently, a Scene is rendered with transparency, and has a clear background color by default. Then, `GameViewController` sets a background of *its* view to black, in order to get a black scene.

This should be changed, so that `GameViewController` doesn't have to do anything, and instead we should make `Scene` have a black background color by default, which should also enable us to always render a scene without transparency. This should give us a slight performance boost as Core Animation doesn't have to include alpha in the layer's backing.

**Things to do here:**

- Remove the code that sets background colors from `GameViewController` on both iOS/tvOS + macOS.
- Make `Scene` have a black background color per default instead of `clear`.
- Enable `isOpaque` on the scene's layer.

**Comment by z0s** [comment]
Hi John, I submitted a PR with a proposed change. Please let me know if I must make any further additions to solve this issue as this was my first attempt at contributing to open source.

**Comment by JohnSundell** [comment]
@z0s That's awesome - just merged your PR! 😄 Congrats on making your first open source contribution 🎉
