### ISSUE TITLE
Add 'enteredScene' event for actors

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#57]
`Actor` already has a `leftScene` event that gets triggered whenever it leaves the bounds of its scene. We should add a `enteredScene` as well that gets triggered whenever an actor moves from being completely outside of its scene to being within its bounds.

**Good to know:**

- Actor events are defined on `ActorEventCollection`.
- The `leftScene` event is triggered by `Scene` in `actorRectDidChange()`, which each actor calls whenever its rect was changed.
- `Actor` has a `isWithinScene` property that is used to track whether an actor is currently within its scene's bounds or not.

**Comment by Warren-Lamb** [comment]
Hi John.  I have never done anything like this before.  I solved this issue by adding  this code to ActorEventCollection.swift

/// Event triggered when the actor collided with any other actor
    public private(set) lazy var collidedWithAnyActor = Event<Actor, Actor>(object: self.object)
 then  the following to Scene.swift

if !wasWithinScene && actor.isWithinScene {
            actor.events.enteredScene.trigger()
        }

<img width="872" alt="screen shot 2017-11-09 at 11 27 17 pm" src="https://user-images.githubusercontent.com/33536650/32642955-c33342a4-c5a5-11e7-9fa3-4642e4a71b29.png">
<img width="1116" alt="screen shot 2017-11-09 at 11 30 17 pm" src="https://user-images.githubusercontent.com/33536650/32642989-18124946-c5a6-11e7-891c-4700b7225f6c.png">

**Comment by JohnSundell** [comment]
@Warren-Lamb Looks great 👍 Perhaps do an `else if` since the actor can't both enter and exit the scene at the same time. Then we should also add some tests to make sure this works as expected. Can you open a PR with your changes and we can discuss it further there? 😄

**Comment by JohnSundell** [comment]
Fixed by @Warren-Lamb in https://github.com/JohnSundell/ImagineEngine/pull/60
