### ISSUE TITLE
Add 'actorAdded' event on Scene

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#68]
In order to be able to observe whenever an actor was added to a scene, it would be awesome to have an event for it. That way really cool plugins could be written, like this:

```swift
class ColorAllActorsPlugin: Plugin {
    func activate(for scene: Scene, in game: Game) {
        scene.events.actorAdded.observe { scene, actor in
            actor.backgroundColor = .red
        }
    }
}
```

The above plugin would add a red background color to all actors that are added to the scene that the plugin is attached to. Very useful to implement things like debug tools 👍

**Things to do:**

- Add a new event on `SceneEventCollection` for when an actor was added (see the other events for inspiration).
- Trigger the event when a new actor is added to a scene.

**Comment by z0s** [comment]
Hi John, please let me know if I might take additional steps at this point. Thanks!



<img width="682" alt="SceneEventCollection" src="https://user-images.githubusercontent.com/13080927/32693391-27b44cde-c6df-11e7-85ee-af07e9ad819c.png">
