### ISSUE TITLE
Texture does not load

### ISSUE THREAD

**Issue by woaiios** [JohnSundell/ImagineEngine#88]
Place image in the workspace. 
![image](https://user-images.githubusercontent.com/4178793/32941343-1d38daf2-cb4b-11e7-98c5-a66674fd2e23.png)

Block

```
let ground = Block(size: size, spriteSheetName: "Ground")
ground.position = center
add(ground)
```

Player

```
let player = Actor()
player.position = center
add(player)
player.textureNamePrefix = "Player/"
        
let idleAnimation = Animation(name: "Idle", frameCount: 1, frameDuration: 1)
```

The ground is visible, but the player is hidden.

**Comment by JohnSundell** [comment]
Hi @woaiios 👋 The problem is that Xcode groups are not translated into real folders in your app's bundle, so the player's idle texture will actually be at the path `/0@2x.png`. To fix this you can use folder references instead of groups, that way a folder will also be created in your app bundle 👍

**Comment by JohnSundell** [comment]
@woaiios Did the above solution work for you, or can I help you in any other way? 🙂 Let me know if this can be closed.

**Comment by woaiios** [comment]
Thank you.
Test passed.
![image](https://user-images.githubusercontent.com/4178793/33001987-eb10078e-cd76-11e7-8f3e-a2ec2fc0524b.png)

**Comment by JohnSundell** [comment]
Awesome 🎉
